name: Front CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js lint, test and coverage
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - working-directory: library_front
        run: |
          yarn install
          yarn test